### ISSUE TITLE
Not active

### ISSUE THREAD

**Issue by jlongster** [jlongster/transducers.js#52]
This repo is not active so I'm testing something

@jlongster

**Comment by jlongster** [comment]
Literally say whatever you want

**Comment by jlongster** [comment]
My notifications aren't working

**Comment by connorlindsey** [comment]
wat

**Comment by markerikson** [comment]
I like turtles 🐢

**Comment by matallo** [comment]
happy to help

**Comment by jasonmit** [comment]
hey James!

**Comment by chaance** [comment]
Tabs > spaces

**Comment by jlongster** [comment]
WHOA CHANCE TOO FAR

**Comment by jlongster** [comment]
thanks everyone I found the bug 😊 

I get notifications in a discord channel from github but they stopped happening.

**Comment by JasonEtco** [comment]
I think I'm too late, but here's a picture of my cat!

![image](https://user-images.githubusercontent.com/10660468/142128109-2a531d89-3322-4b83-8ab6-fa24ff8fdb9e.png)

**Comment by jlongster** [comment]
This is now a cat pic thread

**Comment by some1else** [comment]
I was really stressed when paparazzi wouldn’t stop following me this wk but then I realized it was opportunity to troll .. i swear this headline omg wtf haha im dead

Full disclosure I’m still living with e and I am not a communist (although there are some very smart ideas in this book -but personally I’m more interested in a radical decentralized ubi that I think could potentially be achieved thru crypto and gaming but I haven’t ironed that idea out enough yet to explain it. Regardless my opinions on politics are difficult to describe because the political systems that inspire me the most have not yet been implemented).

Anyway if paparazzi keep chasing me perhaps I will try to think of more ways to meme - suggestions welcome!

![image](https://user-images.githubusercontent.com/10702/142129343-2361c884-d9c9-4332-af53-b8b55b1788b3.png)

**Comment by rickhanlonii** [comment]
whatever you want

**Comment by mbifulco** [comment]
Weeow

**Comment by shulhi** [comment]
Vim > emacs

**Comment by betodealmeida** [comment]
Hello!

**Comment by ppkn** [comment]
This is a picture of the best cat I've ever met
![my favorite cat](https://user-images.githubusercontent.com/6591123/142131190-121265ea-f7b1-4e2a-bf3c-9942cead45bc.jpg)

**Comment by fitsum** [comment]
gulpfile in the repo, I know
I know it's serious

**Comment by fitsum** [comment]
Gulpfile in the repo, I know
I know
I know it's serious

**Comment by JeremyJaydan** [comment]
my cat smeg
![image](https://user-images.githubusercontent.com/15324232/142133984-8fb98bd6-10ed-43d4-86e0-bb61128bd512.png)

**Comment by mikekreuzer** [comment]
+1

**Comment by Chudesnov** [comment]
just my cat looking silly
![68BDF382-87A4-4CEE-95F5-C191A3AA8B0C](https://user-images.githubusercontent.com/240422/142139246-f84763ba-3f5d-4463-b61d-91d6a3ab0202.jpeg)

**Comment by The-Blue-Wizard** [comment]
Oooh, those cats! I love them!

**Comment by valscion** [comment]
I raise thee a puppy

![IMG_20200618_215742](https://user-images.githubusercontent.com/482561/142152622-da7ae664-3da4-4757-95e0-de2ae7a47b12.jpg)

**Comment by TrySound** [comment]
Hey Dude, don't make it bad.
Take a sad song and make it better.
Remember to let her into your heart,
Then you can start to make it better.

**Comment by mookerific** [comment]
Test comment!

**Comment by cloud-walker** [comment]
+1

**Comment by wodin** [comment]
![Cat](https://user-images.githubusercontent.com/4579020/142235707-b4dd1ff0-3a45-4867-9a1a-f4f18bff56a9.png)

**Comment by BinRoot** [comment]
pr approved, lgtm

**Comment by pqt** [comment]
how do I exit vim? I tried buying a new laptop but that didn't work.

**Comment by pramodadpushup** [comment]
Test data

**Comment by jlongster-stripe** [comment]
test
